version: "3.9"

services:
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
    - "8000:8000"
    environment:
      - USER_NAME=user
      - PASSWORD=password
      - DATABASE=db
      - PORT=5432
      - DATABASE_NAME=app_db
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:14.22-trixie
    container_name: postgres_db
    ports:
    - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge